/**
 * Modal for creating a new consent definition.
 * Slug is auto-generated by the backend from the name.
 */

import { useState } from 'react';
import styled from 'styled-components';
import { Modal } from '@/common/components/Modal/Modal';
import { Button } from '@/common/components/Button/Button';
import { FormGrid, FieldGroup, Label, Input, TextArea, ErrorMessage } from '@/common/components/Form/Form';
import { t } from '@/common/i18n';
import type { ProtocolStage } from '../types';
import { useCreateDefinition } from '../hooks/useConsents';

interface CreateDefinitionModalProps {
    isOpen: boolean;
    onClose: () => void;
}

const STAGE_OPTIONS: { value: ProtocolStage; label: string }[] = [
    { value: 'CHECK_IN', label: 'Przyjęcie (CHECK_IN)' },
    { value: 'CHECK_OUT', label: 'Wydanie (CHECK_OUT)' },
];

export const CreateDefinitionModal = ({ isOpen, onClose }: CreateDefinitionModalProps) => {
    const [name, setName] = useState('');
    const [description, setDescription] = useState('');
    const [stage, setStage] = useState<ProtocolStage>('CHECK_IN');
    const [isMandatory, setIsMandatory] = useState(false);
    const [errors, setErrors] = useState<Record<string, string>>({});

    const { createDefinition, isCreating, error: apiError } = useCreateDefinition({
        onSuccess: () => {
            handleClose();
        },
    });

    const handleClose = () => {
        setName('');
        setDescription('');
        setStage('CHECK_IN');
        setIsMandatory(false);
        setErrors({});
        onClose();
    };

    const validateForm = () => {
        const newErrors: Record<string, string> = {};

        if (!name.trim()) {
            newErrors.name = t.consents.validation.nameRequired;
        } else if (name.length < 3) {
            newErrors.name = t.consents.validation.nameMin;
        } else if (name.length > 100) {
            newErrors.name = t.consents.validation.nameMax;
        }

        if (description.length > 500) {
            newErrors.description = t.consents.validation.descriptionMax;
        }

        setErrors(newErrors);
        return Object.keys(newErrors).length === 0;
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();

        if (!validateForm()) {
            return;
        }

        createDefinition({
            name: name.trim(),
            description: description.trim() || undefined,
            stage,
            isMandatory,
        });
    };

    return (
        <Modal
            isOpen={isOpen}
            onClose={handleClose}
            maxWidth="600px"
            title={t.consents.createDefinitionModal.title}
        >
            <ModalHeader>
                <ModalTitle>{t.consents.createDefinitionModal.title}</ModalTitle>
            </ModalHeader>

            <Form onSubmit={handleSubmit}>
                <FormGrid>
                    <FieldGroupFull>
                        <Label>
                            {t.consents.createDefinitionModal.nameLabel}
                            <RequiredStar>*</RequiredStar>
                        </Label>
                        <Input
                            type="text"
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            placeholder={t.consents.createDefinitionModal.namePlaceholder}
                            disabled={isCreating}
                            $hasError={!!errors.name}
                        />
                        {errors.name && <ErrorMessage>{errors.name}</ErrorMessage>}
                    </FieldGroupFull>

                    <FieldGroup>
                        <Label>
                            Etap wizyty
                            <RequiredStar>*</RequiredStar>
                        </Label>
                        <Select
                            value={stage}
                            onChange={(e) => setStage(e.target.value as ProtocolStage)}
                            disabled={isCreating}
                        >
                            {STAGE_OPTIONS.map((opt) => (
                                <option key={opt.value} value={opt.value}>
                                    {opt.label}
                                </option>
                            ))}
                        </Select>
                    </FieldGroup>

                    <FieldGroup>
                        <Label>Obowiązkowa</Label>
                        <CheckboxLabel>
                            <Checkbox
                                type="checkbox"
                                checked={isMandatory}
                                onChange={(e) => setIsMandatory(e.target.checked)}
                                disabled={isCreating}
                            />
                            <CheckboxText>Wymagana do podpisania przez klienta</CheckboxText>
                        </CheckboxLabel>
                    </FieldGroup>

                    <FieldGroupFull>
                        <Label>{t.consents.createDefinitionModal.descriptionLabel}</Label>
                        <TextArea
                            value={description}
                            onChange={(e) => setDescription(e.target.value)}
                            placeholder={t.consents.createDefinitionModal.descriptionPlaceholder}
                            disabled={isCreating}
                            rows={3}
                            $hasError={!!errors.description}
                        />
                        {errors.description && <ErrorMessage>{errors.description}</ErrorMessage>}
                    </FieldGroupFull>
                </FormGrid>

                {apiError && (
                    <ErrorMessage>{t.consents.error.createDefinitionFailed}</ErrorMessage>
                )}

                <ModalActions>
                    <Button
                        type="button"
                        $variant="secondary"
                        onClick={handleClose}
                        disabled={isCreating}
                    >
                        {t.consents.createDefinitionModal.cancel}
                    </Button>
                    <Button type="submit" $variant="primary" disabled={isCreating}>
                        {isCreating
                            ? t.consents.createDefinitionModal.submitting
                            : t.consents.createDefinitionModal.submit}
                    </Button>
                </ModalActions>
            </Form>
        </Modal>
    );
};

const ModalHeader = styled.div`
    margin-bottom: ${(props) => props.theme.spacing.lg};
`;

const ModalTitle = styled.h2`
    font-size: 1.5rem;
    font-weight: 600;
    color: ${(props) => props.theme.colors.text};
    margin: 0;
`;

const Form = styled.form`
    display: flex;
    flex-direction: column;
    gap: ${(props) => props.theme.spacing.lg};
`;

const FieldGroupFull = styled(FieldGroup)`
    grid-column: 1 / -1;
`;

const RequiredStar = styled.span`
    color: ${(props) => props.theme.colors.error};
    margin-left: 4px;
`;

const Select = styled.select`
    height: 38px;
    border-radius: ${(props) => props.theme.radii.md};
    border: 1.5px solid ${(props) => props.theme.colors.border};
    padding: 0 ${(props) => props.theme.spacing.sm};
    font-family: inherit;
    font-size: 0.875rem;
    color: ${(props) => props.theme.colors.text};
    background: ${(props) => props.theme.colors.surface};
    outline: none;
    cursor: pointer;
    width: 100%;

    &:focus {
        border-color: ${(props) => props.theme.colors.primary};
    }

    &:disabled {
        opacity: 0.6;
        cursor: not-allowed;
    }
`;

const CheckboxLabel = styled.label`
    display: flex;
    align-items: center;
    gap: ${(props) => props.theme.spacing.sm};
    cursor: pointer;
    margin-top: ${(props) => props.theme.spacing.xs};
`;

const Checkbox = styled.input`
    width: 16px;
    height: 16px;
    cursor: pointer;
    accent-color: ${(props) => props.theme.colors.primary};

    &:disabled {
        cursor: not-allowed;
    }
`;

const CheckboxText = styled.span`
    font-size: 0.875rem;
    color: ${(props) => props.theme.colors.text};
`;

const ModalActions = styled.div`
    display: flex;
    gap: ${(props) => props.theme.spacing.md};
    justify-content: flex-end;
    margin-top: ${(props) => props.theme.spacing.md};
`;
