export { SubscriptionSettingsPage } from './pages/SubscriptionSettingsPage';
export { FeatureGate } from './components/FeatureGate';
export { ModuleGate } from './components/ModuleGate';
export { FirstLoginModal } from './components/FirstLoginModal';
export { useFeature } from './hooks/useFeature';
export { useCapability } from './hooks/useCapability';
export { RequireCapability } from './components/RequireCapability';
export { PaywallListener } from './components/PaywallListener';
export { UpsellModal } from './components/UpsellModal';
export { useEntitlements, useStartTrial } from './api/subscriptionQueries';
export type { FeatureKey, FeatureStatus, CapabilityKey, CapabilityStatus } from './types';
