import type { ProtocolTemplate, ProtocolRule } from '../types';

export const mockProtocolTemplates: ProtocolTemplate[] = [
  {
    id: 'pt-1',
    name: 'Regulamin ogólny',
    description: 'Ogólny regulamin świadczenia usług detailingu',
    templateUrl: '/templates/regulamin-ogolny.pdf',
    isActive: true,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'pt-2',
    name: 'Oświadczenie o stanie pojazdu',
    description: 'Dokument przyjęcia pojazdu ze szczegółowym opisem stanu',
    templateUrl: '/templates/oswiadczenie-stan.pdf',
    isActive: true,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'pt-3',
    name: 'Zgoda na korekta lakieru',
    description: 'Zgoda klienta na przeprowadzenie korekty lakieru',
    templateUrl: '/templates/zgoda-korekta.pdf',
    isActive: true,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'pt-4',
    name: 'Gwarancja korekty lakieru',
    description: 'Warunki gwarancji dla usługi korekty lakieru',
    templateUrl: '/templates/gwarancja-korekta.pdf',
    isActive: true,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'pt-5',
    name: 'Protokół wydania pojazdu',
    description: 'Dokument potwierdzający wydanie pojazdu klientowi',
    templateUrl: '/templates/protokol-wydania.pdf',
    isActive: true,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'pt-6',
    name: 'Zgoda na powłokę ceramiczną',
    description: 'Zgoda i warunki aplikacji powłoki ceramicznej',
    templateUrl: '/templates/zgoda-ceramika.pdf',
    isActive: true,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'pt-7',
    name: 'Gwarancja powłoki ceramicznej',
    description: 'Warunki gwarancji dla powłoki ceramicznej (2-5 lat)',
    templateUrl: '/templates/gwarancja-ceramika.pdf',
    isActive: true,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'pt-8',
    name: 'Instrukcja pielęgnacji',
    description: 'Instrukcja pielęgnacji po wykonaniu usługi',
    templateUrl: '/templates/instrukcja-pielegnacji.pdf',
    isActive: true,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
];

export const mockProtocolRules: ProtocolRule[] = [
  // Global CHECK_IN rules
  {
    id: 'pr-1',
    protocolTemplateId: 'pt-1',
    protocolTemplate: mockProtocolTemplates[0],
    triggerType: 'GLOBAL_ALWAYS',
    stage: 'CHECK_IN',
    serviceIds: [],
    serviceNames: [],
    isMandatory: true,
    displayOrder: 1,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'pr-2',
    protocolTemplateId: 'pt-2',
    protocolTemplate: mockProtocolTemplates[1],
    triggerType: 'GLOBAL_ALWAYS',
    stage: 'CHECK_IN',
    serviceIds: [],
    serviceNames: [],
    isMandatory: true,
    displayOrder: 2,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  // Global CHECK_OUT rules
  {
    id: 'pr-3',
    protocolTemplateId: 'pt-5',
    protocolTemplate: mockProtocolTemplates[4],
    triggerType: 'GLOBAL_ALWAYS',
    stage: 'CHECK_OUT',
    serviceIds: [],
    serviceNames: [],
    isMandatory: true,
    displayOrder: 1,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'pr-4',
    protocolTemplateId: 'pt-8',
    protocolTemplate: mockProtocolTemplates[7],
    triggerType: 'GLOBAL_ALWAYS',
    stage: 'CHECK_OUT',
    serviceIds: [],
    serviceNames: [],
    isMandatory: false,
    displayOrder: 2,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  // Service-specific rules (Paint Correction + Detailing)
  {
    id: 'pr-5',
    protocolTemplateId: 'pt-3',
    protocolTemplate: mockProtocolTemplates[2],
    triggerType: 'SERVICE_SPECIFIC',
    stage: 'CHECK_IN',
    serviceIds: ['service-1', 'service-3'], // Korekta lakieru, Detailing kompleksowy
    serviceNames: ['Korekta lakieru', 'Detailing kompleksowy'],
    isMandatory: true,
    displayOrder: 3,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'pr-6',
    protocolTemplateId: 'pt-4',
    protocolTemplate: mockProtocolTemplates[3],
    triggerType: 'SERVICE_SPECIFIC',
    stage: 'CHECK_OUT',
    serviceIds: ['service-1'], // Korekta lakieru
    serviceNames: ['Korekta lakieru'],
    isMandatory: true,
    displayOrder: 3,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  // Service-specific rules (Ceramic Coating)
  {
    id: 'pr-7',
    protocolTemplateId: 'pt-6',
    protocolTemplate: mockProtocolTemplates[5],
    triggerType: 'SERVICE_SPECIFIC',
    stage: 'CHECK_IN',
    serviceIds: ['service-2'], // Powłoka ceramiczna
    serviceNames: ['Powłoka ceramiczna'],
    isMandatory: true,
    displayOrder: 4,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'pr-8',
    protocolTemplateId: 'pt-7',
    protocolTemplate: mockProtocolTemplates[6],
    triggerType: 'SERVICE_SPECIFIC',
    stage: 'CHECK_OUT',
    serviceIds: ['service-2'], // Powłoka ceramiczna
    serviceNames: ['Powłoka ceramiczna'],
    isMandatory: true,
    displayOrder: 4,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
];
